author             = "Ian Pratt <ianjdpratt@gmail.com>"
base_url           = "https://cogsandsquigs.dev"          # The URL the site will be built for
build_search_index = true                                 # Whether to build a search index to be used later on by a JavaScript library
compile_sass       = true                                 # Whether to automatically compile all Sass files in the sass directory
default_language   = "en"
description        = "My little slice of the blogosphere"
feed_filenames     = ["atom.xml", "rss.xml"]
generate_feeds     = true
minify_html        = true
title              = "Cogs & Squigs"

[markdown]
    render_emoji = true # When set to "true", emoji aliases are translated in the rendered Markdown files. (e.g.: :smile: => 😄)

    [markdown.highlighting]
        highlight = true   # Whether to do syntax highlighting
        theme     = "nord" # Theme can be customised by setting this variable to a theme supported by Zola

[[taxonomies]]
    feed = true
    name = "tags"

[[taxonomies]]
    feed = true
    name = "series"

[extra]
    # Put all your custom variables here
