name: publish
on:
    push:
        branches: [main]

jobs:
    publish:
        runs-on: codeberg-tiny
        steps:
            - uses: actions/checkout@v4
            - uses: https://github.com/DeterminateSystems/nix-installer-action@main
            - run: nix build .
            - uses: https://codeberg.org/git-pages/action@v2
              with:
                  site: https://cogsandsquigs.dev/
                  server: codeberg.page
                  token: ${{ forge.token }}
                  source: result/
