name: publish
on:
    push:
        branches: [main]

jobs:
    publish:
        runs-on: codeberg-small
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-zola@v1
              with:
                  zola-version: 0.23.6
            - uses: https://codeberg.org/git-pages/action@v2
              with:
                  site: https://cogsandsquigs.dev/
                  server: codeberg.page
                  token: ${{ forge.token }}
                  source: result/
