name: publish
on:
    push:
        branches: [main]

jobs:
    publish:
        runs-on: codeberg-small
        steps:
            - uses: actions/checkout@v4
            - uses: https://github.com/DeterminateSystems/nix-installer-action@main
            - run: nix build .
            # The below command is required because although nix builds to `result` it's symmlinked,
            # and because the next action runs in a separate container, we move from the build
            # output (`result`) to something not symliked (`static`, default for zola normally)
            - run: cp -rL --no-preserve=mode,ownership result static
            - uses: https://codeberg.org/git-pages/action@v2
              with:
                  site: https://cogsandsquigs.dev/
                  server: codeberg.page
                  token: ${{ forge.token }}
                  source: static/
