description = "My theme for my website."
homepage    = "https://codeberg.org/cogsandsquigs/cogsandsquigs.dev/src/branch/main/themes/cogs"
name        = "cogs"

demo        = "https://cogsandsquigs.dev" # An optional live demo URL
license     = "MIT"
min_version = "0.22.1"                    # The minimum version of Zola required
tags        = []

# The theme author info: you!
[author]
    homepage = "https://cogsandsquigs.dev"
    name     = "Ian Pratt"

# Any variable there can be overridden in the end user `zola.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
    # Any and all links you want to display, in the order you want to display them. These are
    # objects with the following type signature:
    # 
    # ```
    # {
    #     title = "The name of the link",
    #     href = "The url it links to"
    # }
    # ```
    # 
    # By default, there aren't any.
    nav_externals = []
