description = "My theme for my website."
homepage    = "https://codeberg.org/cogsandsquigs/cogsandsquigs.dev/src/branch/main/themes/cogs"
name        = "cogs"

demo        = "https://cogsandsquigs.dev" # An optional live demo URL
license     = "MIT"
min_version = "0.22.1"                    # The minimum version of Zola required
tags        = []

# The theme author info: you!
[author]
    homepage = "https://cogsandsquigs.dev"
    name     = "Ian Pratt"

# Any variable there can be overridden in the end user `zola.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
    # All theme-related configuration is here!
    [extra.theme]
        # The date formatting string. This follows the `chrono` formatting convention.
        # See here: https://docs.rs/chrono/latest/chrono/format/strftime/
        date_format = "%B %-d, %Y"

        # Any and all links you want to display, in the order you want to display them. These are
        # objects with the following type signature:
        # 
        # ```
        # {
        #     title = "The name of the link",
        #     href = "The url it links to"
        # }
        # ```
        # 
        # By default, there aren't any.
        nav_externals = []

        # Configure KaTeX support & rendering. 
        [extra.theme.katex]
            # Enable KaTeX rendering. Off by default.
            enable = false

            # If KaTeX is enabled, auto-render math on page. True by default. Note that turning this
            # off means that you will need to manually insert javascript to render any math on the
            # page. However, the KaTeX library for doing so will be available to you.
            #
            # See: https://katex.org/docs
            auto_render = true
